os:
  - linux
sudo: false
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - add-on
  - extra

licenses:
    - 'android-sdk-license-.+'
jdk:
- oraclejdk8
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter build apk
#  - find -type f -name "*.apk"
  - mv ./build/app/outputs/apk/release/app-release.apk ./TwrpBuilder-Flutter-$(git describe --tags).apk
cache:
  directories:
    - $HOME/.pub-cache
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 8e34bb4b42972600fb53c00981fe8e9af1201570
  file: ./TwrpBuilder-Flutter-$(git describe --tags).apk
  on:
    tags: true