os:
  - linux
sudo: false
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-28
  - add-on
  - extra

licenses:
    - 'android-sdk-license-.+'
jdk:
- oraclejdk8
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter build apk
#  - find -type f -name "*.apk"
  - mv ./build/app/outputs/apk/release/app-release.apk ./TwrpBuilder-Flutter-$(git describe --tags).apk
cache:
  directories:
    - $HOME/.pub-cache
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "PHZ+6bOjti7AMXSYhDdDbX2nzADYvn9ejuFbgLJg3TznK+sdvKiRQdGHsTECJHfAuqEbDDaBKbGQI1JCmBN7aH/mwzdTiXI8Td4l0bxNut6aNNeY4Ag3HuGPfxXh3vFJB01kay8Y9e0yHncpC+cnx8pNcv6pc5ttj2FiIK3mo6BhBsJ3VfXf6FsTMN1ow2VyWvu1mACxNBdfSBr3LIDkKqE/uXqW2JavQSzIuaGOqGNoYK7CWj18OrftJXSGpoHCKF7Q6tNFLTgagKx1i93rBKP9tEKBOJ8xPrG8qIeWLiF7+NCVwfY3fgYchDfJtQZiG+UTZHDa4WDrSKDFjnys3dJCjIOBvpXVQBiMkp/T5eElDA1lHU6dIVhlkaNKV0XsO/skaUUDsDT+x4735/LBbTAefghAqkJy6Dj9sy6apZVMXnVElqORaWzBbrCbhSkcuIrL9ukBoXHaIsYNfaRuc3nLGpDn0bWmlcGIoZ/tDnPb8tGvQzLMh1cO4Qq7FFkEQw/tPcIYOxnUOkvAkN7gWebukPUofCtmOJvc3fjOI6KgZhlF3ADJFGNSEy71IjTeb+mCIH9atHHqqUre3clDccuY4oAebQj56+mdKKJerMlvmmeqJ0ide1VOzM46UABsyAMKiAPvdhnRaS1wUaH3zUwfdRFBT7FXi10rHRhouSM="
  file: ./TwrpBuilder-Flutter-$(git describe --tags).apk
  on:
    tags: true