name: twrp_builder
description: TWRP Builder app
version: 1.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in: "^3.0.4"
  firebase_auth: "^0.5.12"
  firebase_database: ^1.0.2
  firebase_messaging: ^1.0.4
  url_launcher: ^3.0.3
  twrpbuilder_plugin: ^1.0.6
  scoped_model: "^0.2.0"
  shared_preferences: ^0.4.2
  http: ^0.11.3+16
  flushbar: ^0.7.5
  path_provider: ^0.4.1
  flutter_downloader: ^0.1.0
  simple_permissions: ^0.1.6
  flutter_launcher_icons: "^0.5.2"
  document_chooser: ^0.0.2

flutter_icons:
    android: true
    image_path: "assets/ic_launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - locale/i18n_ar.json
    - locale/i18n_en.json
    - locale/i18n_tr.json

  fonts:
      - family: MyFlutterApp
        fonts:
          - asset: fonts/MyFlutterApp.ttf
      - family: Raleway
        fonts:
          - asset: fonts/Raleway-Black.ttf
          - asset: fonts/Raleway-BlackItalic.ttf
            style: italic
          - asset: fonts/Raleway-Bold.ttf
          - asset: fonts/Raleway-BoldItalic.ttf
            style: italic
          - asset: fonts/Raleway-ExtraBold.ttf
          - asset: fonts/Raleway-ExtraBoldItalic.ttf
            style: italic
          - asset: fonts/Raleway-ExtraLight.ttf
          - asset: fonts/Raleway-ExtraLightItalic.ttf
            style: italic
          - asset: fonts/Raleway-Italic.ttf
            style: italic
          - asset: fonts/Raleway-Light.ttf
          - asset: fonts/Raleway-LightItalic.ttf
            style: italic
          - asset: fonts/Raleway-Medium.ttf
          - asset: fonts/Raleway-MediumItalic.ttf
            style: italic
          - asset: fonts/Raleway-Regular.ttf
          - asset: fonts/Raleway-SemiBold.ttf
          - asset: fonts/Raleway-SemiBoldItalic.ttf
            style: italic
          - asset: fonts/Raleway-Thin.ttf
          - asset: fonts/Raleway-ThinItalic.ttf
            style: italic